# Generated by Django 3.1 on 2020-03-19 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toGo', '0002_auto_20200318_2047'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Projects',
        ),
    ]
